services:
  master:
    image: kimdat546/dst-server:latest
    container_name: dst-master-dang-tien
    network_mode: host
    environment:
      DST_CLUSTER_TOKEN: "pds-g^KU_6FZh9CMJ^LbZ7Uf6J62OeOpGA2lY1A6qmzFcSbVeLkzXqyLyz77c="
      DST_NETWORK_CLUSTER_NAME: "uncompromising"
      DST_NETWORK_CLUSTER_DESCRIPTION: "uncompromising"
      DST_NETWORK_CLUSTER_PASSWORD: "haizz"
      DST_GAMEPLAY_MAX_PLAYERS: "12"
      DST_GAMEPLAY_GAME_MODE: "endless"
      DST_NETWORK_SERVER_PORT: "11999"
      DST_SHARD_ENABLED: "true"
      DST_SHARD_IS_MASTER: "true"
      DST_SHARD_NAME: "Master"
      DST_SHARD_BIND_IP: "0.0.0.0"
      DST_SHARD_MASTER_IP: "127.0.0.1"
      DST_SHARD_MASTER_PORT: "11888"
      DST_SHARD_CLUSTER_KEY: "neverland_cluster"
      DST_SERVER_MOD_SETUP: "1111658995,1207269058,1595631294,1780476441,1803285852,1982562290,2010472942,2039181790,2496686961,2847908822,3004639365,3353852416,3360553731,3390560378,3670669065,3675508496,3688913682,374550642,375850593,380423963,501385076,666155465"
    volumes:
      - dst-master-data-dang-tien:/var/lib/game
      - ./config/Master/modoverrides.lua:/etc/dst-config/Master/modoverrides.lua:ro
      - ./config/Master/leveldataoverride.lua:/etc/dst-config/Master/leveldataoverride.lua:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "grep", "-q", "shard_enabled = true", "/var/lib/game/server/general/cluster.ini" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s

  caves:
    image: kimdat546/dst-server:latest
    container_name: dst-caves-dang-tien
    network_mode: host
    environment:
      DST_CLUSTER_TOKEN: "pds-g^KU_6FZh9CMJ^LbZ7Uf6J62OeOpGA2lY1A6qmzFcSbVeLkzXqyLyz77c="
      DST_NETWORK_CLUSTER_NAME: "uncompromising"
      DST_NETWORK_SERVER_PORT: "11998"
      DST_SHARD_ENABLED: "true"
      DST_SHARD_IS_MASTER: "false"
      DST_SHARD_NAME: "Caves"
      DST_SHARD_BIND_IP: "0.0.0.0"
      DST_SHARD_MASTER_IP: "127.0.0.1"
      DST_SHARD_MASTER_PORT: "11888"
      DST_SHARD_CLUSTER_KEY: "neverland_cluster"
      DST_SERVER_MOD_SETUP: "1111658995,1207269058,1595631294,1780476441,1803285852,1982562290,2010472942,2039181790,2496686961,2847908822,3004639365,3353852416,3360553731,3390560378,3670669065,3675508496,3688913682,374550642,375850593,380423963,501385076,666155465"
    volumes:
      - dst-caves-data-dang-tien:/var/lib/game
      - ./config/Caves/modoverrides.lua:/etc/dst-config/Caves/modoverrides.lua:ro
      - ./config/Caves/leveldataoverride.lua:/etc/dst-config/Caves/leveldataoverride.lua:ro
    depends_on:
      master:
        condition: service_healthy
    restart: unless-stopped

volumes:
  dst-master-data-dang-tien:
  dst-caves-data-dang-tien:
