return {
  ["workshop-1111658995"]={ configuration_options={  }, enabled=true },
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-1595631294"]={
    configuration_options={
      BundleItems=false,
      ChangeSkin=true,
      Digornot=false,
      DragonflyChest=false,
      Icebox=false,
      OnlyPlayer=false,
      SaltBox=false 
    },
    enabled=true 
  },
  ["workshop-1780476441"]={ configuration_options={  }, enabled=true },
  ["workshop-1803285852"]={
    configuration_options={
      [""]=0,
      AutoPickupAsh=false,
      AutoPickupEnabled=false,
      AutoPickupPoop=false,
      AutoPickupRange=10,
      AutoPickupSeeds=false,
      AutoStackAsh=true,
      AutoStackEnabled=true,
      AutoStackMakeNewStackMainStack=false,
      AutoStackManuallyDroppedItems=true,
      AutoStackPoop=true,
      AutoStackRange=10,
      AutoStackSeeds=true,
      AutoStackTwiggyTreeTwigs=true,
      ManualDropStackRange=5,
      ManualStackAsh=true,
      ManualStackMakeNewStackMainStack=true,
      ManualStackPoop=true,
      ManualStackSeeds=true,
      PlayerMustHaveOneOfItemToAutoPickup=false,
      SmokePuffOnStacking=true,
      StackDuringPopulation=true
    },
    enabled=true 
  },
  ["workshop-2334209327"]={
    configuration_options={
      ALCOHOLICDRINKS=true,
      AUTORETROFIT=false,
      COFFEEDROPRATE=4,
      COFFEEDURATION=480,
      COFFEESPEED=true,
      EXPERIMENTAL=false,
      EXTRAS=false,
      FERTILIZERTWEAK=false,
      FULLMOONTRANS=false,
      GENERAL=false,
      GIANTSPAWNING=true,
      HUMANMEAT=true,
      ICEBOXSTACKSIZE=false,
      KEEPFOOD=false,
      LANGUAGE="vi",
      MEADOW_CC=0,
      MODTRADES=true,
      RETROCOMPAT=false,
      SCRAPBOOK=true,
      SCRAPBOOK2=false,
      SEASONALFOOD=false,
      SERENITY_CC=0,
      WARLYMEALGRINDER=false,
      WARLYRECIPES=true,
      WARLYSPICES=false 
    },
    enabled=true 
  },
  ["workshop-3353852416"]={
    configuration_options={
      CH_LANG=false,
      CountdownEnable=false,
      HomesignEnable=true,
      HungerCost=0,
      LightEnable=true,
      ResurrectEnable=true,
      SanityCost=0,
      TeleportEnable=true,
      TextEnable=false 
    },
    enabled=true 
  },
  ["workshop-374550642"]={
    configuration_options={
      FORCE_STACKSIZES=false,
      STACK_SIZE_LARGEITEM=99,
      STACK_SIZE_MEDITEM=99,
      STACK_SIZE_PELLET=120,
      STACK_SIZE_SMALLITEM=99,
      STACK_SIZE_TINYITEM=99 
    },
    enabled=true 
  },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-380423963"]={
    configuration_options={
      [""]=0,
      boulder_blue=0.75,
      boulder_purple=0.75,
      change_cave_loot=false,
      common_loot_charcoal=0,
      common_loot_flint=0.35,
      common_loot_rocks=0.35,
      cutlichen=0,
      durian=0,
      flintless_blue=0.75,
      flintless_purple=0.75,
      flintless_red=0.75,
      foliage=0,
      gears=0,
      goldvein_purple=0.75,
      goldvein_red=0.75,
      guano=0,
      ice=0,
      lightbulb=0,
      moon_green=0.5,
      moon_orange=0.5,
      moon_yellow=0.5,
      pinecone=0,
      rare_loot_bluegem=0.3,
      rare_loot_marble=0.3,
      rare_loot_redgem=0.3,
      rottenegg=0,
      seeds=0,
      spoiled_food=0,
      stalagmite_green=0.5,
      stalagmite_orange=0.5,
      stalagmite_yellow=0.5,
      uncommon_loot_goldnugget=0.2,
      uncommon_loot_mole=0.2,
      uncommon_loot_nitre=0.2,
      uncommon_loot_rabbit=0.2 
    },
    enabled=true 
  },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true 
    },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  } 
}