return {
  ["workshop-1530801499"]={
    configuration_options={
      ArrowsignEnable=false,
      CountdownEnable=false,
      HungerCost=0,
      Ownership=true,
      SanityCost=0
    },
    enabled=true
  },
  ["workshop-1780476441"]={ configuration_options={  }, enabled=true },
  ["workshop-1803285852"]={
    configuration_options={
      [""]=0,
      AutoPickupAsh=false,
      AutoPickupEnabled=false,
      AutoPickupPoop=false,
      AutoPickupRange=10,
      AutoPickupSeeds=false,
      AutoStackAsh=true,
      AutoStackEnabled=true,
      AutoStackMakeNewStackMainStack=false,
      AutoStackManuallyDroppedItems=true,
      AutoStackPoop=true,
      AutoStackRange=10,
      AutoStackSeeds=true,
      AutoStackTwiggyTreeTwigs=true,
      ManualDropStackRange=10,
      ManualStackAsh=true,
      ManualStackMakeNewStackMainStack=true,
      ManualStackPoop=true,
      ManualStackSeeds=true,
      PlayerMustHaveOneOfItemToAutoPickup=false,
      SmokePuffOnStacking=true,
      StackDuringPopulation=false 
    },
    enabled=true 
  },
  ["workshop-3004639365"]={
    configuration_options={
      [""]=0,
      ["Alcohol Drinks Brewing"]=0,
      alcohol_time=0.5,
      beer_wait=0.75,
      ["Brewery options"]=0,
      butterhunter_time=0.25,
      caffein_speed=1.25,
      caffein_time=1,
      capacity_time=0.5,
      child_safety=true,
      ["Coffee Speed Boost"]=0,
      ["Drink Alcohol Capacity"]=0,
      ["Drink Alcohol Effect"]=0,
      ["Drink Butterhunter Effect"]=0,
      ["Drink O.B.E. Effect"]=0,
      ["Drink Sleep Effect"]=0,
      drunkard_time=0.5,
      ["Effect options"]=0,
      enable_thirst=true,
      enable_waterborne=true,
      gen_caffeinberry=1.2,
      gen_ruincacao_tree=1.2,
      gen_tea_tree=1.2,
      ghost_time=0.25,
      immune_time=0.5,
      locale="vi",
      max_capacity=5,
      re_retrofit=0,
      resistance_time=0.5,
      ["Select Language"]=0,
      sleeping_time=15,
      ["Soda Brewing"]=0,
      soda_wait=0.75,
      ["Thirst options"]=0,
      thirst_decrease_speed=0.6,
      thirst_max=150,
      useinsight=true,
      useshowme=true,
      waterborne_time=0.5,
      ["WorldGen options"]=0 
    },
    enabled=true 
  },
  ["workshop-3235319974"]={
    configuration_options={
      key_v=118,
      key_x=120,
      key_z=122,
      set00=0,
      set1=true,
      set10=5,
      set11=true,
      set12=1,
      set13=false,
      set2=true,
      set3=true,
      set4=false,
      set5=true,
      set6=true,
      set7=true,
      wukongkey=114 
    },
    enabled=true 
  },
  ["workshop-374550642"]={
    configuration_options={
      FORCE_STACKSIZES=false,
      STACK_SIZE_LARGEITEM=99,
      STACK_SIZE_MEDITEM=99,
      STACK_SIZE_PELLET=250,
      STACK_SIZE_SMALLITEM=99,
      STACK_SIZE_TINYITEM=120
    },
    enabled=true 
  },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-380423963"]={
    configuration_options={
      [""]=0,
      boulder_blue=0.75,
      boulder_purple=0.75,
      change_cave_loot=false,
      common_loot_charcoal=0,
      common_loot_flint=0.35,
      common_loot_rocks=0.35,
      cutlichen=0,
      durian=0,
      flintless_blue=0.75,
      flintless_purple=0.75,
      flintless_red=0.75,
      foliage=0,
      gears=0,
      goldvein_purple=0.75,
      goldvein_red=0.75,
      guano=0,
      ice=0,
      lightbulb=0,
      moon_green=0.5,
      moon_orange=0.5,
      moon_yellow=0.5,
      pinecone=0,
      rare_loot_bluegem=0.3,
      rare_loot_marble=0.3,
      rare_loot_redgem=0.3,
      rottenegg=0,
      seeds=0,
      spoiled_food=0,
      stalagmite_green=0.5,
      stalagmite_orange=0.5,
      stalagmite_yellow=0.5,
      uncommon_loot_goldnugget=0.2,
      uncommon_loot_mole=0.2,
      uncommon_loot_nitre=0.2,
      uncommon_loot_rabbit=0.2 
    },
    enabled=true 
  },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true 
    },
    enabled=true 
  } 
}